import assert from 'node:assert/strict';
import {seed,draft,parse,recommendations,matches,accept,advance} from './engine.ts';
let db=seed();assert.equal(db.users.length,10);assert.equal(db.foods.length,30);assert.equal(db.restaurants.length,15);assert.equal(db.routes.length,8);assert.equal(db.orders.length,10);
const q=parse('我今天不想吃太油，150 元內，而且希望 40 分鐘內吃到。',{budget:180,minutes:45,mood:'隨便',prefs:['不吃辣'],exclude:[],text:''});assert.equal(q.budget,150);assert.equal(q.minutes,40);const rec=recommendations(db,q);assert.ok(rec.length>=3);for(const r of rec){assert.ok(r.food.price+25<=150);assert.ok(r.eta<=40);assert.ok(!r.food.tags.includes('油炸'));}
assert.equal(recommendations(db,{...q,budget:10}).length,0);assert.ok(recommendations(db,{...q,prefs:['素食']}).every(r=>r.food.tags.includes('素食')));
let o=draft(db,rec[0].food,40);db={...db,orders:[o,...db.orders]};let m=matches(db,o)[0];assert.ok(m);db=accept(db,o.id,m.route.id);assert.throws(()=>accept(db,o.id,m.route.id));while(db.orders[0].status<6)db=advance(db,o.id);assert.throws(()=>advance(db,o.id,'xxxx'));db=advance(db,o.id,o.code);assert.equal(db.orders[0].status,7);assert.equal(db.foods.find(f=>f.id===o.foodId).stock,11);assert.throws(()=>advance(db,o.id,o.code));assert.ok(db.orders[0].completedAt);
let sold=seed();let so=draft(sold,sold.foods[0]);sold.orders.unshift(so);sold=accept(sold,so.id,matches(sold,so)[0].route.id);sold=advance(sold,so.id);sold=advance(sold,so.id);sold.foods[0].stock=0;assert.throws(()=>advance(sold,so.id));sold.orders[0].replacement=true;assert.throws(()=>advance(sold,so.id));
let capped=seed();capped.routes[0].capacity=1;const a=capped.orders.find(x=>x.buyerId!==capped.routes[0].userId);capped=accept(capped,a.id,capped.routes[0].id);const b=capped.orders.find(x=>x.status===0&&x.buyerId!==capped.routes[0].userId);assert.equal(matches(capped,b,[capped.routes[0]]).length,0);assert.equal(matches(capped,{...b,deadline:Date.now()-1}).length,0);
console.log('PASS: seed counts; budget/deadline/preferences; impossible query; match; duplicate acceptance; complete timeline; wrong code; stock deduction; sold-out; capacity; expired deadline.');
