export type Point={x:number;y:number};
export type User={id:string;name:string;rating:number;completed:number};
export type Restaurant={id:string;name:string;category:string;point:Point};
export type Food={id:string;restaurantId:string;name:string;price:number;tags:string[];category:string;stock:number};
export type Route={id:string;userId:string;start:Point;end:Point;storeId:string;departure:number;detour:number;capacity:number};
export type Order={id:string;buyerId:string;foodId:string;item:string;storeId:string;price:number;fee:number;destination:string;point:Point;deadline:number;status:number;runnerId?:string;routeId?:string;code:string;created:number;messages:{role:string;text:string}[];ratings:Record<string,number>;tags:Record<string,string[]>;cancelled?:boolean;replacement?:boolean;detour?:number;completedAt?:number;matchedAt?:number;etaMinutes?:number};
export type Profile={name:string;location:string;preferences:string[];banned:string;notifications:boolean;history:string[]};
export type DB={version:1;users:User[];restaurants:Restaurant[];foods:Food[];routes:Route[];orders:Order[];profile:Profile;groupMembers:string[]};
export const places:Record<string,Point>={'國立臺灣大學':{x:0,y:0},'台大男一舍':{x:0.3,y:0.4},'台大女九舍':{x:0.2,y:0.3},'台大社科院':{x:0.5,y:0.6},'公館捷運站':{x:0.1,y:-0.4},'家・溫州街':{x:-0.3,y:0.3},'公司・公館':{x:0.2,y:-0.2}};
const menus:[string,string,string,number,string[],string,number,string[]][]=[
['小日子雞肉飯','台式','雞肉飯＋燙青菜',110,['清爽','雞','均衡'],'滷肉飯便當',100,['豬','重口味']],
['藍家割包','台式','割包＋四神湯',115,['豬','熱熱的'],'雙份割包',130,['豬','吃飽']],
['巷口牛肉麵','麵食','紅燒牛肉麵',160,['牛','熱熱的','重口味'],'番茄牛肉湯麵',155,['牛','熱熱的']],
['日和咖哩','日式','雞肉咖哩飯',135,['雞','吃飽'],'蔬菜咖哩飯',120,['素食','均衡']],
['首爾食堂','韓式','韓式豬肉拌飯',145,['豬','辣','重口味'],'雞肉湯飯',140,['雞','熱熱的']],
['綠盒子','健康餐','舒肥雞胸餐',125,['雞','高蛋白','清爽','均衡'],'豆腐蔬食餐',115,['素食','清爽','均衡']],
['阿姨便當','便當','烤雞腿便當',115,['雞','高蛋白'],'炸排骨便當',110,['豬','油炸']],
['越好吃','麵食','牛肉河粉',125,['牛','熱熱的','清爽'],'鮮蔬河粉',110,['素食','熱熱的','清爽']],
['一碗烏龍','日式','豆皮烏龍麵',110,['素食','熱熱的'],'豬肉烏龍麵',130,['豬','熱熱的']],
['蒸好食','台式','鮮肉湯包',100,['豬','熱熱的'],'蔬菜蒸餃',95,['素食','清爽']],
['幸福小鍋','火鍋','豬肉小火鍋',180,['豬','熱熱的','吃飽'],'蔬食小火鍋',160,['素食','熱熱的']],
['飯糰研究所','日式','鮭魚飯糰套餐',105,['魚','清爽'],'海苔豆腐飯糰',90,['素食','清爽']],
['椒香食堂','便當','椒麻雞飯',145,['雞','辣','油炸','重口味'],'蒜香豬肉飯',130,['豬','重口味']],
['水源水餃','麵食','高麗菜水餃',90,['豬','清爽'],'韭菜水餃',90,['豬']],
['日日蔬食','健康餐','彩虹蔬菜碗',120,['素食','均衡','清爽'],'豆腐藜麥碗',130,['素食','高蛋白','清爽']]];
export const statuses=['尋找代買者','媒合成功','前往店家','抵達店家','已購買','配送中','已抵達','已完成'];
export function seed():DB {const users=['Gary','羽欣','Kevin','Mia','小安','Yuki','Leo','Nina','Eric','小宇'].map((name,i)=>({id:'u'+i,name,rating:4.7+(i%3)/10,completed:12+i*4}));const restaurants=menus.map((m,i)=>({id:'r'+i,name:m[0],category:m[1],point:{x:(i%5)*0.12-0.15,y:Math.floor(i/5)*0.12-0.22}})); const foods=menus.flatMap((m,i)=>[0,1].map(j=>({id:'f'+(i*2+j),restaurantId:'r'+i,name:String(m[j?5:2]),price:Number(m[j?6:3]),tags:m[j?7:4] as string[],category:m[1],stock:12})));const now=Date.now();return {version:1,users,restaurants,foods,routes:Array.from({length:8},(_,i)=>({id:'route'+i,userId:'u'+(i+1),start:{x:-0.15+i*.04,y:-0.35},end:{x:.3,y:.45},storeId:i<3?'':'r'+i,departure:now+(i%3)*60000,detour:15,capacity:3})),orders:Array.from({length:10},(_,i)=>({id:'D'+(1001+i),buyerId:'u'+(i+1)%10,foodId:'f'+(i%5)*2,item:foods[(i%5)*2].name,storeId:'r'+(i%5),price:foods[(i%5)*2].price,fee:25+i%3*5,destination:'台大男一舍',point:places['台大男一舍'],deadline:now+60*60000,status:0,code:String(3840+i),created:now-i*5000,messages:[],ratings:{},tags:{}})),profile:{name:'Gary',location:'國立臺灣大學',preferences:['不吃辣'],banned:'',notifications:true,history:[]},groupMembers:['u1','u2','u3']};}
export const distance=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y);
export function matches(db:DB,o:Order,routes=db.routes){return routes.map(r=>{const store=db.restaurants.find(s=>s.id===o.storeId)!;const active=db.orders.filter(x=>x.routeId===r.id&&!x.cancelled&&x.status>0&&x.status<7);const extra=Math.max(0,Math.ceil((distance(r.start,store.point)+distance(store.point,o.point)+distance(o.point,r.end)-distance(r.start,r.end))*12));const wait=Math.max(0,(r.departure-Date.now())/60000);const eta=Math.ceil(wait+distance(r.start,store.point)*12+12+distance(store.point,o.point)*12+active.length*4);const rating=db.users.find(u=>u.id===r.userId)?.rating??4.8;const score=Math.round(40+Math.max(0,25-extra)+Math.min(15,o.fee/3)+rating*3);return {route:r,extra,eta,score:Math.min(99,score)};}).filter(m=>m.route.userId!==o.buyerId&&(!m.route.storeId||m.route.storeId===o.storeId)&&m.extra<=m.route.detour&&Date.now()+m.eta*60000<=o.deadline&&db.orders.filter(x=>x.routeId===m.route.id&&!x.cancelled&&x.status>0&&x.status<7).length<m.route.capacity).sort((a,b)=>b.score-a.score);}
export type Query={budget:number;minutes:number;mood:string;prefs:string[];exclude:string[];text:string};
export function parse(text:string,base:Query):Query{let q={...base,text,exclude:[...base.exclude],prefs:[...base.prefs]};const b=text.match(/(\d+)\s*(?:元|塊|以內|以下)/);if(b)q.budget=Number(b[1]);const t=text.match(/(\d+)\s*分鐘/);if(t)q.minutes=Number(t[1]);if(/清爽|不.*油|健康/.test(text))q.mood='清爽';if(/湯|熱熱/.test(text))q.mood='熱熱的';if(/爽一點|重口味/.test(text))q.mood='重口味';for(const x of ['雞','牛','豬','魚'])if(text.includes('不想吃'+x)||text.includes('不吃'+x))q.exclude.push(x);if(/素食/.test(text))q.prefs.push('素食');if(/不吃辣|不要辣/.test(text))q.prefs.push('不吃辣');return q;}
export function recommendations(db:DB,q:Query){return db.foods.filter(f=>f.stock>0&&f.price+25<=q.budget&&!q.exclude.some(x=>f.tags.includes(x)||f.name.includes(x)||f.category===x)&&(!q.prefs.includes('素食')||f.tags.includes('素食'))&&(!q.prefs.includes('不吃辣')||!f.tags.includes('辣'))&&!(q.mood==='清爽'&&f.tags.includes('油炸'))).map(f=>{const store=db.restaurants.find(s=>s.id===f.restaurantId)!;const o=draft(db,f,q.minutes,25);const ms=matches(db,o);const eta=ms[0]?.eta??999;const dist=distance(store.point,o.point);const goals=q.prefs.filter(p=>['高蛋白','減脂','增肌','均衡'].includes(p));const goalMatch=goals.some(p=>f.tags.includes(p==='增肌'?'高蛋白':p==='減脂'?'清爽':p));const moodMatch=f.tags.includes(q.mood)||(q.mood==='想吃肉'&&f.tags.some(t=>['雞','豬','牛','魚'].includes(t)));const pref=Math.min(1,(moodMatch?.8:.25)+(goalMatch?.2:0));const availability=Math.min(1,ms.length/3);const score=Math.round(25*pref+25*availability+15*Math.max(0,1-eta/90)+15*(1-(f.price+25)/q.budget*.4)+10*Math.max(0,1-dist)+10*(db.profile.history.includes(f.category)?0:1));return {food:f,store,score,eta,runners:ms.length,distance:Math.round(dist*1000),reason:[f.tags.includes(q.mood)?'符合你想吃'+q.mood+'的心情':'符合你的飲食設定',db.profile.history.includes(f.category)?'熟悉的口味':'換個口味，吃得更多樣',ms.length+' 位符合條件的順路人選'].join(' · ')};}).filter(x=>x.runners>0&&x.eta<=q.minutes).sort((a,b)=>b.score-a.score);}
export function draft(db:DB,f:Food,minutes=60,fee=25):Order{return {id:'D'+Date.now().toString(36)+Math.random().toString(36).slice(2,5),buyerId:'u0',foodId:f.id,item:f.name,storeId:f.restaurantId,price:f.price,fee,destination:db.profile.location,point:places[db.profile.location]??places['國立臺灣大學'],deadline:Date.now()+minutes*60000,status:0,code:String(Math.floor(1000+Math.random()*9000)),created:Date.now(),messages:[],ratings:{},tags:{}};}
export function accept(db:DB,id:string,routeId:string):DB{const o=db.orders.find(x=>x.id===id);if(!o||o.status!==0||o.cancelled)throw Error('這筆需求已被接走或取消');const m=matches(db,o).find(x=>x.route.id===routeId);if(!m)throw Error('行程已不符合時間、繞路或容量條件');return {...db,orders:db.orders.map(x=>x.id===id?{...x,status:1,runnerId:m.route.userId,routeId,detour:m.extra,matchedAt:Date.now(),etaMinutes:m.eta}:x)};}
export function advance(db:DB,id:string,code?:string):DB {const o=db.orders.find(x=>x.id===id);if(!o||o.cancelled||o.status<1||o.status>=7)throw Error('此訂單無法前進');if(o.replacement)throw Error('請先由 Buyer 確認替代餐點');if(o.status===6&&code!==o.code)throw Error('取餐碼不正確，請再確認');let foods=db.foods;if(o.status===3){const f=foods.find(x=>x.id===o.foodId);if(!f||f.stock<1)throw Error('餐點已售完，請選擇替代餐點');foods=foods.map(x=>x.id===o.foodId?{...x,stock:x.stock-1}:x);}return {...db,foods,orders:db.orders.map(x=>x.id===id?{...x,status:x.status+1,...(x.status===6?{completedAt:Date.now()}:{})}:x),profile:o.status===6?{...db.profile,history:[...db.profile.history,db.foods.find(f=>f.id===o.foodId)?.category??''].slice(-7)}:db.profile};}
export interface Repository {load():DB;save(db:DB):void;}
export const localRepository:Repository={load(){try{const raw=localStorage.getItem('diet-fan-v1');if(raw){const d=JSON.parse(raw);if(d.version===1&&Array.isArray(d.orders)&&Array.isArray(d.foods))return d;}}catch{}return seed();},save(db){localStorage.setItem('diet-fan-v1',JSON.stringify(db));}};
